version: "3"
services:
  api:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_CONFIG_ROOT_USERNAME:admin
      - MONGO_CONFIG_ROOT_PASSWORD:password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    restart: always
    environment:
    # - ME_CONFIG_MONGODB_ADMINUSERNAME:admin
    # - ME_CONFIG_MONGODB_ADMINPASSWORD:password
    - ME_CONFIG_MONGODB_URL:mongo://admin:password@mongo:27017
    depends_on:
      - mongo
volumes:
  mongo-data:
    driver: local

      